apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-dev
  namespace: dev
  labels:
    app: flask-app
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
      env: dev
  template:
    metadata:
      labels:
        app: flask-app
        env: dev
    spec:
      containers:
      - name: flask-app
        image: bibhishandhagate/flask-devops-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: ENV
          value: "dev"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
